#############################################################################
#!
#! This is a tmake template for creating a makefile that invokes make in
#! sub directories - for Unix.
#!
#${
    StdInit();
    Project('MAKEFILE') || Project('MAKEFILE = Makefile');
    Project('TMAKE') || Project('TMAKE = tmake');
#$}
#!
# Makefile for building targets in sub directories.
# Generated by tmake;
#     Project: #$ Expand("PROJECT");
#    Template: #$ Expand("TEMPLATE");
#############################################################################

MAKEFILE=	#$ Expand("MAKEFILE");
TMAKE	=	#$ Expand("TMAKE");

SUBDIRS	=	#$ ExpandList("SUBDIRS");

all: $(SUBDIRS)

$(SUBDIRS): FORCE
	cd $@; $(MAKE)

#$ TmakeSelf();

tmake_all:
#${
		$text = "\t" . 'for i in $(SUBDIRS); do ( if [ -d $$i ]; then cd $$i ; $(MAKE) -f $(MAKEFILE) tmake_all || true; fi; ) ; done';
#$}

####	$text = "\t" . 'for i in $(SUBDIRS); do ( if [ -d $$i ]; then cd $$i ; pro=`basename $$i`.pro ; $(TMAKE) $$pro -o $(MAKEFILE); grep "TEMPLATE.*subdirs" $$pro 2>/dev/null >/dev/null && $(MAKE) -f $(MAKEFILE) tmake_all || true; fi; ) ; done';

clean release debug:
	for i in $(SUBDIRS); do ( if [ -d $$i ]; then cd $$i ; $(MAKE) $@; fi; ) ; done

FORCE:
